routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();


Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/', 'ProjectController@reloadProjectFormDb')->name('home');
    Route::get('/developerlist', 'ProjectController@developer')->name('developerList');
    Route::post('/updateWithSeparateDate', 'ProjectController@updateWithSeparateDate')->name('updateWithSeparateDate');
    Route::get('/getproject', 'ProjectController@getProject')->name('getProject');
    Route::get('/projectlist', 'ProjectController@withOutDeveloper')->name('projectList');
    Route::post('/projectshow', 'ProjectController@projectShow')->name('projectShow');
    Route::get('/reloadTaskFormDb', 'ProjectController@reloadTaskFormDb')->name('reloadTaskFormDb');
    Route::post('/updateProject/{id}', 'ProjectController@updateProject')->name('updateProject');
    Route::post('/developercheck', 'DeveloperController@checkBusy')->name('checkBusy');
    Route::get('/developercheck/{id?}', 'DeveloperController@checkBusyDevUnderDistribution')->name('checkBusyDevUnderDistribution');
    Route::get('/appointmentofdevelopers', 'DeveloperController@appointmentOfDevelopers')->name('appointmentOfDevelopers');
    Route::post('/download', 'ProjectController@download')->name('download');
    Route::match(['get', 'post'], '/project/add/task/{id?}', 'ProjectController@addTask')->name('addTask');
    Route::match(['get', 'post'], '/project/add/developer/{id?}', 'ProjectController@addDev')->name('addDev');
    Route::get('/taskedit', 'TaskController@edit')->name('taskEdit');
    Route::DELETE('/taskdestroy', 'TaskController@destroy')->name('taskDestroy');
    Route::resource('project', 'ProjectController');
    Route::resource('task', 'TaskController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\DescriptionProject;

class Project extends Model
{
    protected $fillable = ['id','title','projectTypeKey','key','description_id','lead','start','end','estimate'];

    public function descriptions(){
        return $this->hasMany('App\DescriptionProject','project_id','id'); // best exam
    }

    public function tasks(){
        return $this->hasMany('App\Task','project_id','id');
    }

    public function developers(){
        return $this->belongsToMany('App\Developer','project_developer', 'project_id', 'developer_id');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\DescriptionTask;
use App\Developer;
use App\PriorityTask;
use App\Project;
use App\Repositories\Project\ProjectRepository;
use App\Specialie;
use App\Task;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\JiraRequestModel\UploadJira;
use Illuminate\Support\Facades\Auth;
use App\DescriptionProject;
use App\Facades\DeveloperFacade;
use App\Facades\TaskFacade;
use App\Facades\ProjectFacade;

class ProjectController extends Controller
{

    /**
     * @var ProjectRepository
     */
    private $projectRepository;

    /**
     * TaskController constructor.
     * @param ProjectRepository $projectRepository
     */
    public function __construct(ProjectRepository $projectRepository)
    {
        $this->projectRepository = $projectRepository;
    }

    /**
     * This method returns all projects.
     * that are assigned to the developers.
     *
     * Return json.
     */
    public function index() {
        return Response()->json($this->projectRepository->getAllProjectAndDeveloper());
    }


    /**
     * This method returns all projects.
     * that are not assigned to developers.
     *
     * Return json.
     */
    public function withOutDeveloper() {
        return Response()->json($this->projectRepository->getAllProjectWithOutDeveloper());
    }


    /**
     * This method returns all developers
     *
     * Return json.
     */
    public function developer() {
        return Response()->json($this->projectRepository->getDeveloper());
    }

    /**
     * This method create or update project.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     *
     * return redirect to rout home.
     */
    public function store(Request $request) {
        $project = isset($request['checkbox']) ? Project::find($request['project']) : new Project();

        $this->projectRepository->create(
            $project,
            isset($request['title']) ? $request['title'] : null,
            isset($request['key']) ? $request['key'] : null,
            isset($request['projectTypeKey']) ? $request['projectTypeKey'] : null,
            isset(Auth::user()->name) ? Auth::user()->name : null,
            $request['start-date'] . " " . $request['start-time'],
            $request['end-date'] . " " . $request['end-time'],
            isset($request['distribution']) ? $request[ 'distribution'] : null
            );

        return redirect()->route('home');
    }

    /**
     * This method show project by id.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response return json
     *
     * return json
     */
    public function getProject(Request $request) {
        $project = Project::find($request->id);

        return response()->json([
            'response' => view('project.infoProject', ['project' => $project] )->render()
        ]);
    }


    /**
     * This method takes two method( Get, Post ).
     *
     * Post returns json includes view which make update or create task.
     *
     * Get returns view main page.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     *
     * Return view.
     */
    public function addTask(Request $request, $id = null) {

        if ($request->isMethod('post')) {
            $priority = PriorityTask::all();
            $project = Project::where('id', '=', $id)->with(['tasks', 'descriptions'])->get();
            $arrDescriptionsOnTheTask =[];


            if (isset($project[0]['descriptions'])) {
                foreach ($project[0]['descriptions'] as $description) {
                    array_push($arrDescriptionsOnTheTask, $description);
                }
            }

            if ($request['id'] != 0) {
                $task= Task::find($request['id']);
                return response()->json([
                    'response' => view('task.task', [
                        'task' => $task,
                        'project_id' => $request['project_id'],
                        'button' => 'Update',
                        'priority' => $priority,
                        'priorityTask' => $task->priority->name,
                        'arrDescriptionsOnTheTask' => $arrDescriptionsOnTheTask,
                        'specialitiesTask' => $task->specialities
                        ]
                    )->render()
                ]);
            } else {
                return response()->json([
                    'response' => view( 'task.task', [
                        'task' => new Task(),
                        'project_id' => $request[ 'project_id' ],
                        'button' => 'Add',
                        'priority' => $priority,
                        ]
                    )->render()
                ] );
            }
        }


        if ($request->isMethod('get')) {
            $project = Project::where('id', '=', $id)->with(['tasks', 'descriptions'])->get();
            $arrTaskOnTheProject =[];
            $arrDescriptionsOnTheTask =[];


            if (isset($project[0]['descriptions'])) {
                foreach ($project[0]['descriptions'] as $description) {
                    array_push($arrDescriptionsOnTheTask, $description);
                }
            }

            if (isset($project[0]['tasks'])) {
                foreach ($project[0]['tasks'] as $task) {
                    array_push($arrTaskOnTheProject, $task);
                }
            }


            $data = [
                'tasks' => Task::get(['id', 'summary','project_id']),
                'project' => Project::find($id),
                'arrDescriptionsOnTheTask' => $arrDescriptionsOnTheTask,
                'arrTaskOnTheProject' => $arrTaskOnTheProject
            ];
            return view("task.addTask",$data);
        }
    }

    /**
     * This method takes two method( Get, Post ).
     *
     * Post returns json includes view.
     * Get returns view main page.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\View\View
     */
    public function addDev(Request $request, $id = null)
    {

        if ($request->isMethod('post')) {
            $developer = Developer::find($request['id']);
            return response()->json([
                'response' => view('developer.developer', ['developer' => $developer, 'level' => $developer->level->name])->render()
            ]);
        }


        if ($request->isMethod('get')) {
            $arrFreeDeveloperOnTheProject =[];
            $arrDescriptionsOnTheProject =[];

            $project = Project::where('id', '=', $id)->with(['developers','descriptions'])->get(); //where('id', '=', $id)->with(['',''])->get()
            $developers = Developer::get(['id', 'title']);




            if (isset($project[0]['descriptions'])) {
                foreach ($project[0]['descriptions'] as $description) {
                    array_push($arrDescriptionsOnTheProject, $description);
                }
            }


            if (isset($project[0]['developers'])) {
                foreach ($project[0]['developers'] as $developer) {
                    array_push($arrFreeDeveloperOnTheProject, $developer);
                    $developers = $this->findInCollectionAndDrop($developers, 'id',  $developer['id']);
                }
            }




            $data = [
                'arrDeveloperOnTheProject' => $developers,
                'project' => Project::find($id),
                'developers' => $arrFreeDeveloperOnTheProject,
                'arrDescriptionsOnTheProject' => $arrDescriptionsOnTheProject
            ];
            return view( "developer.addDeveloper", $data );
        }

    }


    /**
     * This method update project.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     *
     * return json.
     */
    public function projectShow(Request $request) {
        $this->projectRepository->updateDateProject($request->id,  $request->start, $request->end);
        return response()->json(['response' => true ]);
    }

    /**
     * This method update project when date and time was separated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     *
     * return json.
     */
    public function updateWithSeparateDate(Request $request) {
            $project = Project::find($request['id']);
            $this->projectRepository->create(
                $project,
                isset($request[ 'title' ]) ? $request[ 'title' ] : null,
                Auth::user()->name,
                isset($request[ 'key' ]) ? $request[ 'key' ] : null,
                isset($request[ 'projectTypeKey' ]) ? $request[ 'projectTypeKey' ] : null,
                $request['start-date'] . " " . $request['start-time'],
                $request['end-date'] . " " . $request['end-time'],
                isset($request[ 'distribution' ]) ? $request[ 'distribution' ] : null
            );

            return redirect()->route('home');
    }

    /**
     * This method update date-end project when the project size changes in the calendar.
     *
     * @param  \Illuminate\Http\Request $request
     * @param integer $id
     * @return \Illuminate\Http\Response return json.
     *
     * return json.
     */
    public function updateResize(Request $request, $id) {
            $msg = Project::find($id);
            $end = $msg->end;
            $resEnd = Carbon::createFromFormat('Y-m-d H:i:s', $end);
            $msg->end = $resEnd->addSeconds($request->dayDelta);
            $msg->save();
            return response()->json(['response' => true]);
    }

    /**
     * This method destroy Project by id.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $project = Project::find($id);

resources/views/project/createProject.blade.php
{!! Form::open(['route' => 'project.store', 'method' => 'post']) !!}
    <div class="modal-dialog">
        <div class="modal-header">
            <h3>Add Project</h3>
        </div>
        <div class="modal-body">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Title<span style="color:red">*</span></label>
                <div class="col-sm-4">
                    <input type="text" id="nameProject" class="form-control" name="title" placeholder="Name">
                </div>
                <label class="col-sm-2 col-form-label">Title from Jira</label>
                <div class="col-sm-3">
                    <select name="project" id="project">
                        @if(isset($project))
                            @foreach($project as $it)
                                <option value="{{ $it->id }}">{{ $it->title }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
                <input type="checkbox" name="checkbox"  id="open_select_from_jira" class="col-sm-1">
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Start<span style="color:red">*</span></label>
                <div class="col-sm-5">
                    <input type="text" class="form-control datepicker" id="start-date" required name="start-date" placeholder="Date">
                </div>
                <div class="col-sm-5">
                    <input type="text" class="form-control ui-timepicker-input" required value="10:00" name="start-time">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">End<span style="color:red">*</span></label>
                <div class="col-sm-5">
                    <input type="text" class="form-control datepicker" id="end-date" required name="end-date" placeholder="Date">
                </div>
                <div class="col-sm-5">
                    <input type="text" class="form-control ui-timepicker-input" required value="19:00" name="end-time">
                </div>
            </div>
            <div class="form-group row">
                <label  class="col-sm-2 col-form-label">Distribution</label>
                <div class="col-sm-10">
                    <textarea class="form-control" rows="5" name="distribution" id="comment"></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            {!! Form::submit('Add', ['class' => 'btn btn-success']) !!}
        </div>
    </div>
    {!! Form::close() !!}

resources/views/project/distribution.blade.php
@extends('layouts.app')

@section('style')
    @parent
@endsection

@section('script')
    @parent
@endsection


@section('myStyle')
    @parent
    <style>
        #downloadFromJira{
            float: right;
            width: 20px;
            height: 20px;
        }
        #print{
            margin-right: 3%;
            float: right;
            width: 20px;
            height: 20px;
        }
        .alert{
            display: none;
        }
    </style>
@endsection

@section('preloader')
    @parent
@endsection

@section('navBar')
    @parent
@endsection

@section('content')
    @parent
@endsection

@section('myScript')
    @parent
@endsection

resources/views/project/infoProject.blade.php
<div class="form-group row">
    <div class="container-fluid">
        <div class="col-md-6">
            <b>Title:</b><span id="title">{{ isset($project->title)  ? $project->title : "" }}</span></br>
            <b>Lead:</b><span id="lead">{{ isset($project->lead) ? $project->lead : "" }}</span></br>
            <b>Start:</b><span id="start">{{ isset($project->start) ? $project->start : "" }}</span>
            <b>End:</b><span id="end">{{ isset($project->end) ? $project->end : "" }}</span></br>
        </div>
        <div class="col-md-3">
            <p>Developers <img class="add_img"  data-url = "{{ route('addDev', ['id' => isset($project->id) ? $project->id : 1]) }}" src="{{ asset('/public/img/plus-2.png') }}"></p>
            <ul style="padding-left: 0">
                @if(isset($project->developers))
                    @foreach($project->developers as $pr)
                        <li>{{ $pr->title }}</li>
                    @endforeach
                @endif
            </ul>
        </div>
        <div class="col-md-3">
            <p>Tasks <img class="add_img" data-url = "{{ route('addTask', ['id' => isset($project->id) ? $project->id : 1]) }}" src="{{ asset('/public/img/plus-2.png') }}"></p>
            <ul style="padding-left: 0">
                @if(isset($project->tasks))
                    @foreach($project->tasks as $pr)
                        <li>{{ $pr->summary }}</li>
                    @endforeach
                @endif
            </ul>
        </div>
    </div>
</div>
</div>
<div class="modal-footer">
        <button class ='btn btn-danger' data-url = "{{ route('project.destroy', ['id' => isset($project->id) ? $project->id : 1]) }}" id="delete">Delete</button>
        <button class ='btn btn-info' data-url = "{{ route('updateProject', ['id' => isset($project->id) ? $project->id : 1]) }}"  id="updateInfo">Update Information</button>
</div>

resources/views/project/updateProject.blade.php
{!! Form::open(['route' => 'updateWithSeparateDate', 'method' => 'post']) !!}
<div class="modal-dialog">
    <input type="hidden" name="id" value="{{ $project->id }}">
    <div class="modal-header">
        <h3>Add Project</h3>
    </div>
    <div class="modal-body">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Title<span style="color:red">*</span></label>
            <div class="col-sm-4">
                <input type="text" id="nameProject" class="form-control" required value="{{ isset($project->title) ? $project->title : "" }}" name="title" placeholder="Name">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Start<span style="color:red">*</span></label>
            <div class="col-sm-5">
                <input type="text" class="form-control datepicker" id="start-date" name="start-date" value="{{ isset($project->startD) ? $project->startD : "" }}" placeholder="Date">
            </div>
            <div class="col-sm-5">
                    <input type="text" class="form-control ui-timepicker-input" required value="{{ isset($project->startT) ? $project->startT : "" }}"  name="start-time">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">End<span style="color:red">*</span></label>
            <div class="col-sm-5">
                <input type="text" class="form-control datepicker" required id="end-date" value=" {{ isset($project->endD) ? $project->endD : "" }}" name="end-date" placeholder="Date">
            </div>
            <div class="col-sm-5">
                <input type="text" class="form-control ui-timepicker-input" value="{{ isset($project->endT) ? $project->endT : "" }}" required  name="end-time">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Distribution</label>
            <div class="col-sm-10">
                <textarea class="form-control" rows="5" name="distribution" id="comment">{{ isset($project->descriptions) ? $project->descriptions : "" }}</textarea>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}
    </div>
</div>
{!! Form::close() !!}