routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();


Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/', 'ProjectController@reloadProjectFormDb')->name('home');
    Route::get('/developerlist', 'ProjectController@developer')->name('developerList');
    Route::post('/updateWithSeparateDate', 'ProjectController@updateWithSeparateDate')->name('updateWithSeparateDate');
    Route::get('/getproject', 'ProjectController@getProject')->name('getProject');
    Route::get('/projectlist', 'ProjectController@withOutDeveloper')->name('projectList');
    Route::post('/projectshow', 'ProjectController@projectShow')->name('projectShow');
    Route::get('/reloadTaskFormDb', 'ProjectController@reloadTaskFormDb')->name('reloadTaskFormDb');
    Route::post('/updateProject/{id}', 'ProjectController@updateProject')->name('updateProject');
    Route::post('/developercheck', 'DeveloperController@checkBusy')->name('checkBusy');
    Route::get('/developercheck/{id?}', 'DeveloperController@checkBusyDevUnderDistribution')->name('checkBusyDevUnderDistribution');
    Route::get('/appointmentofdevelopers', 'DeveloperController@appointmentOfDevelopers')->name('appointmentOfDevelopers');
    Route::post('/download', 'ProjectController@download')->name('download');
    Route::match(['get', 'post'], '/project/add/task/{id?}', 'ProjectController@addTask')->name('addTask');
    Route::match(['get', 'post'], '/project/add/developer/{id?}', 'ProjectController@addDev')->name('addDev');
    Route::get('/taskedit', 'TaskController@edit')->name('taskEdit');
    Route::DELETE('/taskdestroy', 'TaskController@destroy')->name('taskDestroy');
    Route::resource('project', 'ProjectController');
    Route::resource('task', 'TaskController');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{

    protected $table = 'tasks';
    protected $fillable = ['id','summary','key','color','priority_id','project_id','resolution','status'];


    public function project(){
        return $this->belongsTo('App\Project');
    }

    public function priority(){
        return $this->hasOne('App\PriorityTask','id', 'priority_id');
    }

    public function descriptions(){
        return $this->hasMany('App\DescriptionTask','id', 'description_id');
    }

    public function specialities(){
        return $this->belongsToMany('App\Specialie','task_specialie', 'task_id', 'speciality_id');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\DescriptionTask;
use App\Repositories\Task\TaskRepository;
use App\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{

    /**
     * @var TaskRepository
    */
    private $taskRepository;

    /**
     * TaskController constructor.
     * @param TaskRepository $taskRepository
     */
    public function __construct(TaskRepository $taskRepository)
    {
        $this->taskRepository = $taskRepository;
    }


    /**
     * This method returns task view.
     *
     * Return view.
     */
    public function index()
    {
        return view("task.task");
    }


    /**
     * This method creates new task.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     *
     * Return make redirect on step before.
     */
    public function create(Request $request) {
        $task = $request->all();
        $this->taskRepository->createOrUpdate(
                isset($task['id_Task']) ? $task['id_Task'] : null,
                isset($task['summary']) ? $task['summary'] : null,
                isset($task['key']) ? $task['key'] : null,
                isset($task['resolution']) ? $task['resolution'] : null,
                isset($task['status']) ? $task['status'] : null,
                '#fff',
                isset($task['priority']) ? $task['priority'] : null,
                isset($task['descriptions']) ? $task['descriptions'] : null,
                isset($task['labels']) ? $task['labels'] : null,
                isset($task['project_id']) ? $task['project_id'] : null
            );


        $url = route("addTask", ["id" => $task[ 'project_id' ]]);
        return redirect($url);
    }


    /**
     * This method assigns tasks to the project
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     *
     * return json
     */
    public function edit(Request $request) {
        if ($request->isMethod('GET')) {
            return response()->json([
                'response' => $this->taskRepository->appointmentOfTasks($request['tasks'], $request['id'])
            ]);
        }
    }


    /**
     * This method makes destroy Task.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response return json
     *
     * return json
     */
    public static function destroy(Request $request) {
        $task = Task::find($request['id']);
        $task->specialities()->detach();
        $task->delete();

        DescriptionTask::where('task_id', $request['id'])->delete();

        return response()->json(['response' => true]);
    }

}

resources/views/task/addTask.blade.php
@extends('layouts.app')

@section('style')
    <link href='{{ asset('/public/css/app.css') }}' rel='stylesheet' />
    <link href='{{ asset('/public/css/fc.css') }}' rel='stylesheet' />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href='{{ asset('/public/lib/jquery.qtip.custom/jquery.qtip.min.css') }}' rel='stylesheet' />
    <link href='{{ asset('/public/lib/fullcalendar.css') }}' rel='stylesheet' />

    <!-- ClockPicker Stylesheet -->
    <link href='{{ asset('/public/lib/bootstrap-datetimepicker.min.css') }}' rel='stylesheet' />
    <link href='{{ asset('/public/lib/fullcalendar.print.css') }}' rel='stylesheet' />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href='{{ asset('/public/lib/fullcalendar-scheduler-1.6.2/scheduler.css') }}' rel='stylesheet' />
    <link href='{{ asset('/public/css/task.css') }}' rel='stylesheet' />
@endsection

@section('script')
    <script src='{{ asset('/public/lib/jquery-ui-1.12.1.custom/external/jquery/jquery.js') }}'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src='{{ asset('/public/lib/lib/jquery.min.js') }}'></script>
    <script src='{{ asset('/public/js/task/task.js') }}'></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- ClockPicker script -->
    <script>
        $ = jQuery.noConflict(false);
    </script>
    <script>
        window.Laravel = <?php echo json_encode([
                'csrfToken' => csrf_token(),
        ]); ?>
    </script>
    <script>
        var csrf_token = "{{ csrf_token() }}";
        var BASEURL = "{{ route('home') }}";
        var linkTaskJs = "{{ asset('/public/js/task/task.js') }}";
        var linkTaskCss = "{{ asset('/public/css/task.css') }}";
        var addTask = "{{ route('addTask') }}";
        var taskEdit = "{{ route('taskEdit') }}";
        var taskDestroy = "{{ route('taskDestroy') }}";
        $(window).on('load', function () {
            var $preloader = $('#page-preloader'),
                $spinner   = $preloader.find('.spinner');
                $spinner.fadeOut();
                $preloader.delay(350).fadeOut('slow');
        });
    </script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
@endsection


@section('myStyle')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <style>
        .layer {
            overflow: scroll;
            width : 300px;
            height : 150px;
            padding : 2px;
            overflow-x: hidden;
        }
    </style>
    <style>
        #sortable1, #sortable2 {
            border: 1px solid #eee;
            width: 142px;
            min-height: 220px;
            list-style-type: none;
            margin: 0;
            padding: 5px 0 0 0;
            float: left;
            margin-right: 10px;
        }
        #sortable1 li, #sortable2 li {
            margin: 0 5px 5px 5px;
            padding: 5px;
            font-size: 1.2em;
            width: 120px;
        }
        .alert{
            display: none;
        }
    </style>
@endsection

@section('preloader')
    @parent
@endsection

@section('navBar')
    @parent
@endsection



@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Task
                        <button type="button" style="float: right;" data-id="0" id="addNewTask" class="btn btn-default btn-xs" aria-label="Left Align">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Task
                        </button>
                    </div>

                    <div class="panel-body row">
                        <div class="col-md-3">
                            <ul id="sortable1" class="connectedSortable">
                                @if(isset($tasks))
                                @foreach($tasks as $task)
                                    @if($task->project_id === 1)
                                            <li class="ui-state-default" style="position: relative"><p>{{ $task->summary }} <img style="position: absolute; bottom: 2px; right: 2px; float: right; width: 15%" src="{{ asset('/public/img/jobSearch.png') }}" data-id="{{ isset($task->id) ?  $task->id  : "" }}"></p></li>
                                        @endif
                                    @endforeach
                                @endif
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <ul id="sortable2" class="connectedSortable">
                                @if(isset($arrTaskOnTheProject))
                                    @foreach($arrTaskOnTheProject as $task)
                                        <li class="ui-state-default" style="position: relative"><p>{{ $task->summary }} <img style="position: absolute;  bottom: 2px; right: 2px; float: right; width: 15%" src="{{ asset('/public/img/jobSearch.png') }}" data-id="{{ isset($task->id) ?  $task->id  : ""}}"></p></li>
                                    @endforeach
                                @endif
                            </ul>
                        </div>

                        <div class="col-md-6">
                            <p><b>Owner  </b><img src="{{ asset('/public/img/user.png') }}" id="project_Owner" data-id="{{ isset($project->id) ? $project->id : "" }}">{{ isset($project->lead) ?  $project->lead : ""}}</p>
                            @if(isset($project->name))
                                <p><b>Title </b>{{ $project->name }}</p>
                            @endif
                            <p><b>Descriptions </b>
                                <div class="layer">
                                    <ul>
                                        @if(isset($arrDescriptionsOnTheTask))
                                            @foreach($arrDescriptionsOnTheTask as $description)
                                                    <li><p>{{ isset($description->name) ? $description->name : ""  }}</p></li>
                                            @endforeach
                                        @endif
                                    </ul>
                                </div>
                            </p>
                            <p><b>Start </b>{{ isset($project->start) ? $project->start : "" }}</p>
                            <p><b>End </b>{{ isset($project->end) ? $project->end : "" }}</p>
                            <p style="float: right"><button id="butSendToDb" class="btn btn-success">Add</button></p>
                        </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="alert alert-success col-md-6 col-md-offset-3">
        Successfully added to the database.
    </div>
    <div class="alert alert-danger col-md-6 col-md-offset-3">
        Error added to the database.
    </div>
    <div id='dialog' data-project-id="{{ isset($project->id) ? $project->id : 1 }}">
        <div class="modal-dialog" id="div1">

        </div>
    </div>
@endsection

@section('myScript')
    <script src='{{ asset('/public/js/task/addTask.js') }}'></script>
@endsection

resources/views/task/task.blade.php
<div class="modal-header">
    <h3>{{ $button }} Task</h3>
</div>
<form method="get" action="{{ route('task.create') }}" id="form1">
    <input type="hidden" name="id_Task"  value="{{ isset($task->id) ? $task->id : '' }}">
    <input type="hidden" name="project_id" value="{{ isset($project_id ) ? $project_id  : '' }}">
    <div class="modal-body">

    <p><b>Summary<span style="color:red">*</span></b><input name="summary"  class="form-control form-control-sm widthMax" value="{{ isset($task->summary) ? $task->summary : '' }}" required></p>
    <p><b>Key</b><input class="widthMax"  name="key" value="{{ isset($task->key) ? $task->key : '' }}"></p>
    <p><b>Priority<span style="color:red">*</span></b>
        <select class="widthMax selectpicker show-tick" name="priority"  required>
                @if(isset($task->priority->name))
                    @foreach($priority as $it)
                        @if($priorityTask != $it->name)
                            <option value="{{ $it->id }}">{{ $it->name }}</option>
                        @else
                            <option selected value="{{ $it->id }}">{{ $it->name }}</option>
                        @endif
                    @endforeach
                @else
                    @foreach($priority as $it)
                            <option value="{{ $it->id }}">{{ $it->name }}</option>
                    @endforeach
                @endif
        </select>
    </p>
    <p>
        <b>Descriptions</b>
        @if(isset($task->descriptions[0]->name))
            <div class="widthMax layer">
                    @foreach($arrDescriptionsOnTheTask as $descriptions)
                         <textarea name="descriptions" class="form-control" rows="5">{{ isset($descriptions->name) ? $descriptions->name : "" }}</textarea>
                    @endforeach
            </div>
        @else
            <textarea class="form-control" name="descriptions" rows="5"></textarea>
        @endif
    </p>
    <p>
        <b>Resolution</b>
        <textarea name="resolution" class="form-control" rows="5">{{ isset($task->resolution) ? $task->resolution : "" }}</textarea>
    </p>
    <p>
    @if(isset($task->resolution))
        <b>Status</b>
           <input class="widthHalf" name="status" type="text" value="{{ isset($task->status) ? $task->status : "" }}">
    @else
        <b>Status<span style="color:red">*</span></b>
        <input class="widthHalf" name="status" type="text" required>
    @endif
    </p>
    <p>
    @if(isset($task->specialities[0]->name))
        <b>Label</b>
            <input name="jurors" id="jurors" type="text" style="width: 50%;">
            <input type="button" value="->" class="addButton" style="width: 10%;" onclick="add_D();" /> <!-- The 'onclick="add();" will call a the Javascript function add() -->
            <select id="mySelect" name="labels[]" style="width:30%; vertical-align: top; border: 1px solid #b4b4b4; border-radius: 10px" rows="1" multiple="multiple">
            @foreach($specialitiesTask as $specialities)
                <option value="{{ $specialities->name }}">{{ $specialities->name }}</option>
            @endforeach
            </select>
        </b>
    @else
        <b style="width: 10%">Label:</b>
        <input name="jurors" id="jurors" type="text" style="width: 50%;">
        <input type="button" value="->" class="addButton" style="width: 10%;" onclick="add_D();" /> <!-- The 'onclick="add();" will call a the Javascript function add() -->
        <select id="mySelect"  name="labels[]" style="width:30%; vertical-align: top; border: 1px solid #b4b4b4; border-radius: 10px" rows="1" multiple="multiple"></select>
    @endif
    </p>
</div>
<div class="modal-footer">
    <button class ='btn btn-default' id="close">Close</button>
    @if($button == 'Update')
        <button class ='btn btn-danger' data-id ="{{ isset($task->id) ? $task->id : "" }}" id="delete">Delete</button>
    @endif
    <button class ='btn btn-info'  id="add">{{ $button }}</button>
</div>
</form>